swagger: "2.0"
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    version: "1.0.0"
    termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
    - http
paths:
    /user/login:
        post:
            tags:
                - User Module
            summary: Login
            description: API for Login
            parameters:
                - in: body
                  name: body
                  description: Login Payload
                  required: true
                  schema:
                      $ref: "#/definitions/Login"
            produces:
                - application/json
            responses:
                "200":
                    description: Login Successfully
                    schema:
                        $ref: "#/definitions/LoginResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /user/signup:
        post:
            tags:
                - User Module
            summary: Signup
            description: API for Signup
            parameters:
                - in: body
                  name: body
                  description: Signup Payload
                  required: true
                  schema:
                      $ref: "#/definitions/User"
            produces:
                - application/json
            responses:
                "200":
                    description: Signup Successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /user/profile:
        get:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for fetching a user profile
            #produces:
            # - application/json
            responses:
                "200":
                    description: User profile retrieved successully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for updating a user profile
            parameters:
                - in: body
                  name: body
                  description: Update user profile attributes
                  required: true
                  schema:
                      $ref: "#/definitions/UserProfile"
            produces:
                - application/json
            responses:
                "200":
                    description: User profile retrieved successully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error

    /transactions/account:
        get:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Get account balances
            description: API to retrieve the total amount and names for each account
            produces:
                - application/json
            responses:
                "200":
                    description: Account balances retrieved successfully
                    schema:
                        type: array
                        items:
                            $ref: "#/definitions/AccountBalance"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /transactions/account/{accountId}:
        get:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Get account details for current month
            description: API to retrieve detailed information of an account including its transactions for current month
            parameters:
                - in: path
                  name: accountId
                  required: true
                  type: string
                  description: Unique identifier of the account
            produces:
                - application/json
            responses:
                "200":
                    description: Account details retrieved successfully
                    schema:
                        $ref: "#/definitions/AccountDetailsResponse"
                "400":
                    description: Invalid Fields
                "404":
                    description: Account not found
                "500":
                    description: Internal Server Error
    /transactions/categories:
        get:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Get list of transaction categories
            description: API to retrieve a list of possible categories for transactions
            produces:
                - application/json
            responses:
                "200":
                    description: Categories retrieved successfully
                    schema:
                        $ref: "#/definitions/CategoriesResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /transactions/{transactionId}/category:
        put:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Update transaction category
            description: API to update the category of a transaction
            parameters:
                - in: path
                  name: transactionId
                  required: true
                  type: string
                  description: Unique identifier of the transaction to update
                - in: body
                  name: body
                  description: Payload to update the transaction category
                  required: true
                  schema:
                      $ref: "#/definitions/UpdateCategoryRequest"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction category updated successfully
                    schema:
                        $ref: "#/definitions/UpdateCategoryResponse"
                "400":
                    description: Invalid Fields
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
    /transactions/{transactionId}/note:
        put:
            security:
                - Bearer: []
            tags:
                - Transactions
            summary: Update transaction note
            description: API to update the note of a transaction
            parameters:
                - in: path
                  name: transactionId
                  required: true
                  type: string
                  description: Unique identifier of the transaction to update
                - in: body
                  name: body
                  description: Payload to update the transaction note
                  required: true
                  schema:
                      $ref: "#/definitions/UpdateNoteRequest"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction note updated successfully
                    schema:
                        $ref: "#/definitions/UpdateNoteResponse"
                "400":
                    description: Invalid Fields
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
definitions:
    User:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name
            userName:
                type: string
                description: user public name
    Login:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
    ApiResponse:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                    email:
                        type: string
    LoginResponse:
        type: object
        properties:
            token:
                type: string
    UserProfile:
        type: object
        properties:
            userName:
                type: string
    AccountBalance:
        type: object
        properties:
            accountId:
                type: string
                description: Unique identifier for the account
            name:
                type: string
                description: Name of the account
            balance:
                type: number
                format: double
                description: Total balance available in the account
    AccountDetailsResponse:
        type: object
        properties:
            status:
                type: integer
                description: Response status code
            message:
                type: string
                description: Response message
            body:
                type: object
                properties:
                    accountId:
                        type: string
                        description: Unique identifier of the account
                    name:
                        type: string
                        description: Name of the account
                    balance:
                        type: number
                        format: double
                        description: Total balance available in the account
                    transactionsList:
                        type: array
                        items:
                            $ref: "#/definitions/TransactionDetails"
    TransactionDetails:
        type: object
        properties:
            id:
                type: string
                description: Unique identifier of the transaction
            date:
                type: string
                format: date
                description: Date of the transaction
            description:
                type: string
                description: Short description of the transaction
            amount:
                type: number
                format: double
                description: Transaction amount
            balance:
                type: number
                format: double
                description: Account balance after the transaction
            transactionType:
                type: string
                description: Type of the transaction (e.g., debit, credit)
            category:
                type: string
                description: Category of the transaction
            note:
                type: string
                description: Additional notes about the transaction
    CategoriesResponse:
        type: object
        properties:
            status:
                type: integer
                description: Response status code
            message:
                type: string
                description: Response message
            body:
                type: array
                items:
                    $ref: "#/definitions/Category"
    Category:
        type: object
        properties:
            id:
                type: string
                description: Unique identifier for the category
            name:
                type: string
                description: Name of the category
    UpdateCategoryRequest:
        type: object
        properties:
            categoryId:
                type: string
                description: ID of the new category for the transaction
    UpdateCategoryResponse:
        type: object
        properties:
            status:
                type: integer
                description: Response status code
            message:
                type: string
                description: Response message
            body:
                type: object
                properties:
                    transactionId:
                        type: string
                        description: Unique identifier of the updated transaction
                    categoryId:
                        type: string
                        description: Updated category ID of the transaction
    UpdateNoteRequest:
        type: object
        properties:
            note:
                type: string
                description: New note for the transaction
    UpdateNoteResponse:
        type: object
        properties:
            status:
                type: integer
                description: Response status code
            message:
                type: string
                description: Response message
            body:
                type: object
                properties:
                    transactionId:
                        type: string
                        description: Unique identifier of the updated transaction
                    note:
                        type: string
                        description: Updated note of the transaction
